name: flutter_guid
description: Emulates C# Guid. Generate new UUIDs, add variables of type Guid to classes.
version: 0.2.0
homepage: https://github.com/rocket-libs/flutter_guid

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.5
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
